import Head from 'next/head'
import Link from "next/link"
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import testPic from '../public/test.png'
import wewebPic from '../public/weweb.png'
import Project from '../components/Project'
import Images from '../public/bitcoin-store/bitcoin'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>

          <div className={styles.section}>
            <h1>Product design for startups and early-stage companies</h1>
            <p>22-year old currently living in Split, Croatia. Biggest goal is to craft something that is useful and elegant. Technical, occasionally coding.</p>
            <p>Looking to work on great products with great teams. Previous clients include corporations, agencies and startups. Open to EU and US opportunities.</p>
            <p>Full project and experience available on inquiry. Open to relocation.</p>
          </div>

          <Image
            src = {Images.somePic}
            width = '200px'
            height = '200px'
          />
          

          <Project
            title= "WeWeb"
            description= "Build user interfaces on top of databases"
            url = "weweb"
            image = {wewebPic}
          />

          <Project
            title= "Bitcoin Store"
            description= "Simply buy, sell and securely store cryptocurrencies"
            url = "bitcoin-store"
            image = {testPic}
          />

        </div>
      </main>
    </>
  )
}
