import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from "next/link"
import styles from '../styles/Home.module.css'
import testPic from '../public/test.png'
import wewebPic from '../public/weweb.png'
import Project from '../components/Project'
import BitcoinPic from '../public/bitcoin-store/01-00.png'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>

          <div className={styles.section}>
            <h1>Product design for startups and early-stage companies</h1>
            <p>22-year old currently living in Split, Croatia. Want to work on well-built and useful products with great teams. Previous clients include corporations, agencies and startups. Technical, occasionally coding. Open to remote and relocation EU and US opportunities.</p>
            <p>For more info and contact: <a>hi@ivanovicluka.co</a> / <a href='https://twitter.com/lukaivnvc'>twitter</a> / <a href='https://dribbble.com/lukaivanovic'>dribbble</a>.</p>
          </div>
          
          <Project
            title= "WeWeb"
            description= "Build user interfaces on top of databases"
            url = "weweb"
            image = {wewebPic}
            time = "Apr 2022 - present"
          />

          <Project
            title= "Bitcoin Store"
            description= "Simply buy, sell and securely store cryptocurrencies"
            url = "bitcoin-store"
            image = {BitcoinPic}
            time = "Nov 2021 - Jul 2022"
          />

        </div>
      </main>
    </>
  )
}
